# Generated by Django 4.2.4 on 2023-08-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=702059829, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
